import type { Preset } from './types.ts';

export const homeAssistant: Preset = {
  id: 'home-assistant',
  name: 'Home Assistant',
  blurb: 'SMS z automatyzacji przez rest_command; SMS do automatyzacji przez webhook HA',
  kinds: ['webhook_in', 'webhook_out'],
  sample: { to: '48601000001', text: 'Alarm: otwarte drzwi garażu' },
  fields: [
    { path: 'to', label: 'numer albo lista numerów' },
    { path: 'text', label: 'treść SMS-a' },
  ],
  inbound: { to: { path: 'to', fallback: [] }, text: { mode: 'path', path: 'text' }, maxParts: 2, overflow: 'truncate' },
  outbound: { body: { mode: 'json', template: '{"from": {{ from | json }}, "text": {{ text | json }}, "receivedAt": {{ receivedAt | json }}}' } },
  expect: {
    recipients: ['48601000001'], text: 'Alarm: otwarte drzwi garażu',
    outboundJson: { from: '48601000001', text: 'Pomocy, nie działa', receivedAt: '2026-09-02T10:00:00.000Z' },
  },
  sampleSource: 'Home Assistant 2026.2.3, żywa instancja, 2026-09-14: rest_command przyjęty przez bramkę (202), wyzwalacz Webhook odebrał zdarzenie (200)',
  guide: [
    '**Do SMS.** W `configuration.yaml` Home Assistanta:',
    '',
    '```yaml',
    'rest_command:',
    '  sms:',
    '    url: "https://bramka.example/hooks/<identyfikator>"',
    '    method: post',
    '    content_type: "application/json"',
    '    payload: \'{"to": {{ to | to_json }}, "text": {{ text | to_json }}}\'',
    '```',
    '',
    'Filtr `to_json` sam zakłada cudzysłowy. Dzięki temu treść z cudzysłowem albo z przełamaniem wiersza nie psuje ładunku. W `to` wolno wtedy podać jeden numer albo listę numerów.',
    '',
    'Po dodaniu bloku uruchom Home Assistanta od nowa. Samo przeładowanie konfiguracji YAML nie wystarczy, bo nie wczytuje nowej integracji. Późniejsze zmiany w bloku wystarczy przeładować akcją `rest_command.reload`.',
    '',
    'W automatyzacji akcja `rest_command.sms` z danymi `to` i `text`. Jeśli chcesz uwierzytelniać nagłówkiem, dodaj `headers: { Authorization: "Bearer <token>" }` i ten sam token w bramce.',
    '',
    '**Z SMS-a.** W automatyzacji wyzwalacz **Webhook** z własnym identyfikatorem; adres integracji wychodzącej to `https://<ha>/api/webhook/<identyfikator>`. Bramka wysyła `from`, `text` i `receivedAt`; w akcjach użyj `{{ trigger.json.text }}`.',
    '',
    'Wyzwalacz webhooka ma domyślnie zaznaczone **Tylko z sieci lokalnej**. Jeśli bramka stoi poza siecią Home Assistanta, odznacz to pole albo dopisz do wyzwalacza `local_only: false`. Bez tego Home Assistant odpowiada kodem 200, a automatyzacja się nie uruchamia - w dzienniku integracji zobaczysz „dostarczono”, choć nic się nie wydarzyło.',
    '',
    'Home Assistant zwykle stoi w sieci lokalnej - bramka domyślnie nie woła takich adresów. Ustaw `MIG_WEBHOOK_ALLOW_PRIVATE=1` albo wystaw HA pod adresem publicznym.',
  ].join('\n'),
};
