import type { Preset } from './types.ts';

export const slack: Preset = {
  id: 'slack',
  name: 'Slack',
  blurb: 'Odebrany SMS jako wiadomość na kanale (webhook przychodzący Slacka)',
  kinds: ['webhook_out'],
  fields: [
    { path: 'from', label: 'numer nadawcy' },
    { path: 'text', label: 'treść SMS-a' },
    { path: 'receivedAt', label: 'czas odbioru' },
  ],
  outbound: {
    url: 'https://hooks.slack.com/services/…',
    body: { mode: 'json', template: '{% capture msg %}SMS od {{ from }}: {{ text }}{% endcapture %}{"text": {{ msg | json }}}' },
  },
  expect: { outboundJson: { text: 'SMS od 48601000001: Pomocy, nie działa' } },
  sampleSource: 'Slack, żywa przestrzeń organizacji, 2026-09-14: aplikacja z manifestu, webhook przychodzący przyjął wiadomość (200 ok, treść widoczna na kanale)',
  guide: [
    '**Aplikacja.** Wejdź na **api.slack.com/apps** oraz kliknij **Create New App**. Wybierz **From a manifest**, wskaż przestrzeń i wklej gotowy opis aplikacji:',
    '',
    '```yaml',
    'display_information:',
    '  name: Multiinfo Gate',
    '  description: SMS odebrane przez bramkę trafiają na kanał',
    'features:',
    '  bot_user:',
    '    display_name: Multiinfo Gate',
    '    always_online: false',
    'oauth_config:',
    '  scopes:',
    '    bot:',
    '      - incoming-webhook',
    'settings:',
    '  org_deploy_enabled: false',
    '  socket_mode_enabled: false',
    '  token_rotation_enabled: false',
    '```',
    '',
    'Manifest wnosi zakres `incoming-webhook`, więc funkcja webhooków jest od razu włączona. Jeśli wolisz bez manifestu, wybierz **Blank app** oraz włącz ją sam w **Features → Incoming Webhooks**.',
    '',
    '**Webhook.** W **Features → Incoming Webhooks** kliknij **Add New Webhook to Workspace**, wybierz kanał i potwierdź przyciskiem **Allow**. Adres `https://hooks.slack.com/services/…` wklej jako adres integracji. Jeden adres obsługuje jeden kanał. Na drugi kanał zrób drugi webhook tym samym przyciskiem.',
    '',
    'Body to `{"text": "…"}`; Slack przyjmuje też bloki (`blocks`), jeśli zmienisz szablon. Nazwę oraz obrazek, pod którymi bramka pisze na kanale, ustawisz w **Basic Information → Display Information**.',
    '',
    'Pozostałych danych z sekcji **App Credentials** bramka nie potrzebuje. Client Secret oraz Signing Secret służą do ruchu w drugą stronę, czyli wtedy, gdy to Slack wysyła żądania do twojej aplikacji.',
    '',
    'Adres webhooka sam w sobie jest hasłem. Kto go ma, ten pisze na kanale. Trzymaj go wyłącznie w bramce, a gdy wyciekł, skasuj webhook w ustawieniach aplikacji oraz zrób nowy.',
    '',
    'W przestrzeni firmowej bywa włączone **Require approved apps**. Wtedy aplikację instaluje osoba z rolą App Manager, czyli właściciel przestrzeni albo ktoś wskazany przez administratora. Zwykły członek może jedynie poprosić o zatwierdzenie. Jeśli nie masz tej roli, poproś administratora Slacka o założenie aplikacji oraz o adres webhooka.',
    '',
    'W katalogu aplikacji Slacka jest też gotowa pozycja **Incoming WebHooks**. Daje ten sam adres, ale to stara integracja. Slack odradza jej zakładanie i zapowiada wycofanie, więc rób własną aplikację.',
  ].join('\n'),
};
